### ISSUE TITLE
audio snippets produce only silence(media projection does not record any audio)

### ISSUE THREAD

**Issue by Engbilal** [julioz/AudioCaptureSample#1]
I am trying to record youtube audio playback. When I play the .pcm file, I cannot hear anything. I am playing the recordings on a pcm player and my audio encoding is the same as in the java code.My android studio version is 3.5.0 and I am running code for android Q.

**Comment by julioz** [comment]
It's very likely Youtube prevents third parties from being able to record their audio. This repository aims to be a showcase on how to implement that functionality and has nothing to do with YouTube or any other individual apps. If you need support on an integration with YouTube, please reach out to Google support.
