### ISSUE TITLE
How to get permission in java ?

### ISSUE THREAD

**Issue by ghost** [julioz/AudioCaptureSample#3]
I am a student.

I want to rewrite this code in java.

for Microphone audio recording I get permission like the following.

    public class Microphone extends AppCompatActivity {

    public static boolean permissionToRecordAccepted = false;
    private static final int REQUEST_RECORD_AUDIO_PERMISSION = 200;
    private String[] permissions = {Manifest.permission.RECORD_AUDIO};

    @SuppressLint("ClickableViewAccessibility")
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_microphone);

        if (this.checkSelfPermission(Manifest.permission.RECORD_AUDIO) != PackageManager.PERMISSION_GRANTED) {
            requestPermissions(permissions, REQUEST_RECORD_AUDIO_PERMISSION);
        } else {
            permissionToRecordAccepted = true;
        }

        if (permissionToRecordAccepted) {
            System.out.println("permission granted.");
        }

    }

    @Override
    public void onRequestPermissionsResult(int requestCode, String permissions[], int[] grantResults) {
        super.onRequestPermissionsResult(requestCode, permissions, grantResults);
        switch (requestCode) {
            case REQUEST_RECORD_AUDIO_PERMISSION:
                permissionToRecordAccepted = (grantResults[0] == PackageManager.PERMISSION_GRANTED);
        }
    }

    }

I want to rewrite this code in java. But , I am confused .

I didn't know how to get permission for internal audio captureing in java.

Can you help me to get permission for internal audio ?

**Comment by julioz** [comment]
Hi @parasuraam, I can help you if you could clarify your question, looking at the code I cannot tell what exactly you are asking for :)

By the way, this repository is simply a showcase to the audio capture API, for general questions on writing Android code you could ask on [StackOverflow](https://stackoverflow.com/questions/tagged/android) or other similar forums. I will keep this issue opened for a few days so I can help you understand the issue, but wanted to clarify this isn't the best place for this kind of question.

**Comment by ghost** [comment]
@julioz Thanks for your reply.

But , I got  answer from another github repository.
